### PR TITLE
Print an error and exit on malformed lines

### PR DESCRIPTION
**Pull request by danieldk**
Not 100% sure if we want to exit with a status code or only print the error and continue running.

### CODE REVIEW

**Comment by sebpuetz** [comment]
I was just writing this comment in the other PR:

I had two things in mind:

1. terminate the program and print usage (3 words on a line seperated by whitespaces)
2. state for the missed query that the query failed.

The second point should probably be extended to the case when the model can't produce an embedding for parts of the query. There it also fails silently. Since we support w2v embeddings and the like, we should probably consider that those models can't handle OOV tokens.

**Comment by danieldk** [comment]
>     1. terminate the program and print usage (3 words on a line seperated by whitespaces)

I don't think unixy programs should print the usage in such cases. There is no tradition to really do that and the usage information is also too verbose.

> The second point should probably be extended to the case when the model can't produce an embedding for parts of the query. There it also fails silently. Since we support w2v embeddings and the like, we should probably consider that those models can't handle OOV tokens.

Agreed. The `finalfusion` API is lacking a bit here. Returning `Option<Embedding>` is ok for returning an embedding (since it is either absent or present). For similarity, returning an `Option` is perhaps ok as well, since the only 'failure' condition is that the token is not known. However, for analogies this is a bit sparse: if the analogy failed, which of the words was missing? Perhaps the analogy method should return something like `Result<Vec<WordSimilarity>, [bool; 3]>` where in the case of `Err` the array indicates which words were present/absent (I don't think there are other failure conditions).

**Comment by sebpuetz** [comment]
> > ```
> > 1. terminate the program and print usage (3 words on a line seperated by whitespaces)
> > ```
> 
> I don't think unixy programs should print the usage in such cases. There is no tradition to really do that and the usage information is also too verbose.

I didn't mean to literally print the usage message, I was thinking about something similar to what you put in the message.

> > The second point should probably be extended to the case when the model can't produce an embedding for parts of the query. There it also fails silently. Since we support w2v embeddings and the like, we should probably consider that those models can't handle OOV tokens.
> 
> Agreed. The `finalfusion` API is lacking a bit here. Returning `Option<Embedding>` is ok for returning an embedding (since it is either absent or present). For similarity, returning an `Option` is perhaps ok as well, since the only 'failure' condition is that the token is not known. However, for analogies this is a bit sparse: if the analogy failed, which of the words was missing? Perhaps the analogy method should return something like `Result<Vec<WordSimilarity>, [bool; 3]>` where in the case of `Err` the array indicates which words were present/absent (I don't think there are other failure conditions).

Sure, makes sense. 

Following this [twitter thread](https://twitter.com/rikvannoord/status/1132933236756238341) (and the related papers), it could also be nice to add a `analogy_unrestricted` method that's allowed to return one of the query tokens, too. Querying through that method could be triggered by a flag on `ff-analogy`.

**Comment by danieldk** [comment]
> Following this [twitter thread](https://twitter.com/rikvannoord/status/1132933236756238341) (and the related papers), it could also be nice to add a `analogy_unrestricted` method that's allowed to return one of the query tokens, too. Querying through that method could be triggered by a flag on `ff-analogy`.

Or maybe `analogy_mask` where you can specify which tokens should be excluded. I didn't read Rik, Malvina, and Rob's paper yet, but probably the most logical candidate to include by default is B, right?

**Pull request merged**
