### PR TITLE
Redo crate features

### PR DESCRIPTION
**Pull request by danieldk**
- Add features for BLAS backends: intel-mkl, netlib, and OpenBLAS.
- Selecting a BLAS backend will automatical enable support for
  optimized product quantizers.
- Force use of OpenBLAS provided by the system.

### CODE REVIEW

**Comment by danieldk** [comment]
```
  = note: /home/travis/build/finalfusion/finalfusion-utils/target/debug/deps/libndarray_linalg-5e61d86e208b5359.rlib(ndarray_linalg-5e61d86e208b5359.ndarray_linalg.eblci1sh-cgu.1.rcgu.o): In function `lapacke::ssyev':
          /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/lapacke-0.2.0/src/lib.rs:21615: undefined reference to `LAPACKE_ssyev'
          /home/travis/build/finalfusion/finalfusion-utils/target/debug/deps/libndarray_linalg-5e61d86e208b5359.rlib(ndarray_linalg-5e61d86e208b5359.ndarray_linalg.eblci1sh-cgu.1.rcgu.o): In function `lapacke::sgesvd':
          /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/lapacke-0.2.0/src/lib.rs:5195: undefined reference to `LAPACKE_sgesvd'
          collect2: error: ld returned 1 exit status
```

Seems OpenBLAS on Ubuntu does not have lapacke symbols.

**Comment by danieldk** [comment]
They indeed build openblas with `NO_LAPACKE=1`.

**Comment by sebpuetz** [comment]
> Still feel sorry for Ubuntu/Debian users. Maybe we should provide precompiled `finalfusion-utils` with an optimized BLAS library. I guess that alternatively we could revert back to not using system OpenBLAS. But I don't really like bundling libraries by default.

Maybe we could provide instructions for Ubuntu/Debian users on how to get a OpenBLAS with lapacke symbols?

**Comment by danieldk** [comment]
> > Still feel sorry for Ubuntu/Debian users. Maybe we should provide precompiled `finalfusion-utils` with an optimized BLAS library. I guess that alternatively we could revert back to not using system OpenBLAS. But I don't really like bundling libraries by default.
> 
> Maybe we could provide instructions for Ubuntu/Debian users on how to get a OpenBLAS with lapacke symbols?

I guess we should do that. There are several options:

* Recompile the Debian/Ubuntu package with the right flags (annoying, because an update would override it).
* Compile OpenBLAS by hand.
* Install Nix ;).

Of course, a BLAS implementation is really only needed for quantizing embeddings with optimized product quantizers. You get some benefits in other places (faster optimized matrix-vector multiplications). But we do not use BLAS by default in sticker, finalfusion-python either. Even though these other projects may benefit as well, since lookups in OPQ embeddings are 3x faster with MKL (I didn't time OpenBLAS yet).

**Pull request merged**
